galaxy_info:
  author: Agafonov Andrey
  description: install and configure haproxy
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - all
  galaxy_tags:
    - haproxy

dependencies:
  - prepare