---
# tasks file for nginx
- name: FILEBEAT | Install Filebeat
  block:
  - name: FILEBEAT |add key for repo
    shell: rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch
    tags:
      - packeges

  - name: FILEBEAT | Delivery template filebeat.repo
    template:
      src: filebeat.repo.j2
      dest: /etc/yum.repos.d/filebeat.repo
      owner: root
      group: root
      mode: '0644'

  - name: FILEBEAT | Install packages
    yum:
      name: "filebeat"
      state: latest
    tags:
      - packages

  - name: FILEBEAT | Create directory for configs
    file:
      path: /etc/filebeat/conf.d
      state: directory
      mode: '0755'

  - name: FILEBEAT | Delivery template filebeat.yml
    template:
      src: "filebeat.yml.j2"
      dest: /etc/filebeat/filebeat.yml
      owner: root
      group: root
      mode: '0644'

  - name: FILEBEAT | Delivery template for app
    template:
      src: "{{filebeat_app_name}}.yml.j2"
      dest: /etc/filebeat/conf.d/{{ filebeat_app_name }}.yml
      owner: root
      group: root
      mode: '0644'
    notify: restart_filebeat

  - name: FILEBEAT | start service
    systemd:
      name: filebeat
      state: started
      enabled: yes


  when: ansible_facts['distribution'] == 'CentOS'
