---
# tasks file for nginx
 - name: FILEBEAT | Install Filebeat
   block:
    - name: FILEBEAT |add key for repo
      shell: rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch
      tags:
        - packeges

    - name: FILEBEAT | Delivery template filebeat.repo
      template:
        src: filebeat.repo.j2
        dest: /etc/yum.repos.d/filebeat.repo
        owner: root
        group: root
        mode: '0644'

    - name: FILEBEAT | Install packages
      yum:
        name: "filebeat"
        state: latest
      tags:
        - packages

    - name: FILEBEAT | Delivery template filebeat.yml
      template:
        src: filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: '0644'

    - name: FILEBEAT | start service
      systemd:
        name: filebeat
        state: started
        enabled: yes


   when: ansible_facts['distribution'] == 'CentOS'
