---
all:
  hosts:
    mdb-erida:
      ansible_host: 172.20.1.28
    mdb-femida:
      ansible_host: 172.20.1.29
    mdb-gestia:
      ansible_host: 172.20.1.30
    mdb-eos:
      ansible_host: 172.20.1.31
    mdb-afrodita:
      ansible_host: 172.20.1.24
    mdb-geya:
      ansible_host: 172.20.1.25
    mdb-clio:
      ansible_host: 172.20.1.26
    mdb-nica:
      ansible_host: 172.20.1.27
    mdb-afina:
      ansible_host: 172.20.1.20
    mdb-fobos:
      ansible_host: 172.20.1.21
    mdb-gera:
      ansible_host: 172.20.1.22
    mdb-deimos:
      ansible_host: 172.20.1.23

  children:
    dns:
      hosts:
        dns-germes:
          ansible_host: 172.20.1.5

    haproxy:
      hosts:
        haproxy-zefs:
          ansible_host: 172.20.1.10
        haproxy-aid:
          ansible_host: 172.20.1.11

    cer:
      hosts:
        cer-appolo:
          ansible_host: 172.20.1.15
        cer-dionis:
          ansible_host: 172.20.1.16
        cer-morphius:
          ansible_host: 172.20.1.17


    mongodb_config:
      hosts:
        mdb-afina:
        mdb-fobos:
        mdb-gera:
        mdb-deimos:

    mongodb_shard1:
      hosts:
        mdb-afrodita:
        mdb-geya:
        mdb-clio:
        mdb-nica:

    mongodb_shard2:
      hosts:
        mdb-erida:
        mdb-femida:
        mdb-gestia:
        mdb-eos:


    gluster:
      hosts:
        gluster-ares:
          ansible_host: 172.20.1.40
        gluster-erot:
          ansible_host: 172.20.1.41
        # gluster-gefest:
        #   ansible_host: 172.20.1.42


    zabbix:
      hosts:
        zabbix-poseidon:
          ansible_host: 172.20.1.220
    kibana:
      hosts:
        kibana-plutos:
          ansible_host: 172.20.1.210

    nfsServer:
      hosts:
        nfs-server1:
          ansible_host: 172.20.1.200

    mongodb:
      children:
        mongodb_router:
        mongodb_config:
        mongodb_shard1:
        mongodb_shard2:

    mongodb_router:
      hosts:
        mdb-afina:
        mdb-fobos:
        mdb-gera:
        mdb-deimos:
...