---
all:
  hosts:
    mdb-bombur:
      ansible_host: 172.20.1.28
    mdb-fili:
      ansible_host: 172.20.1.29
    # mdb-gestia:
    #   ansible_host: 172.20.1.30
    mdb-kili:
      ansible_host: 172.20.1.31
    mdb-bifur:
      ansible_host: 172.20.1.24
    mdb-gloin:
      ansible_host: 172.20.1.25
    mdb-nori:
      ansible_host: 172.20.1.26
    # mdb-nica:
    #   ansible_host: 172.20.1.27
    mdb-torin:
      ansible_host: 172.20.1.20
    mdb-balin:
      ansible_host: 172.20.1.21
    mdb-dvalin:
      ansible_host: 172.20.1.22
    # mdb-deimos:
    #   ansible_host: 172.20.1.23

  children:
    dns:
      hosts:
        dns-germes:
          ansible_host: 172.20.1.5

    haproxy:
      hosts:
        haproxy-radagast:
          ansible_host: 172.20.1.10
        haproxy-gendalf:
          ansible_host: 172.20.1.11

    cer:
      hosts:
        cer-legolas:
          ansible_host: 172.20.1.15
        cer-tauriel:
          ansible_host: 172.20.1.16
        cer-tranduil:
          ansible_host: 172.20.1.17


    mongodb_config:
      hosts:
        mdb-torin:
        mdb-balin:
        mdb-dvalin:
        # mdb-deimos:

    mongodb_shard1:
      hosts:
        mdb-bifur:
        mdb-gloin:
        mdb-nori:
        # mdb-nica:

    mongodb_shard2:
      hosts:
        mdb-bombur:
        mdb-fili:
        mdb-kili:
        # mdb-gestia:


    gluster:
      hosts:
        gluster-bilbo:
          ansible_host: 172.20.1.41
        gluster-frodo:
          ansible_host: 172.20.1.42
        # gluster-gefest:
        #   ansible_host: 172.20.1.42

    prometheus:
      hosts:
        prom-sauron:
          ansible_host: 172.20.1.220

    kibana:
      hosts:
        kibana-elrond:
          ansible_host: 172.20.1.210

    nfsServer:
      hosts:
        nfs-server1:
          ansible_host: 172.20.1.200

    mongodb:
      children:
        mongodb_router:
        mongodb_config:
        mongodb_shard1:
        mongodb_shard2:

    mongodb_router:
      hosts:
        mdb-torin:
        mdb-balin:
        mdb-dvalin:
        #mdb-deimos:

    backup:
      hosts:
        mdb-dvalin:
...