---
- name: add gluster repo
  yum:
    name: centos-release-gluster
    state: present

- name: install gluster client
  yum:
    name:
      - glusterfs
      - glusterfs-fuse
    state: present

- name: check if folder "{{ gluster_backup_dir }}" exists
  stat:
    path: "{{ gluster_backup_dir }}"
  register: check_dir

- debug:
    msg:
      - "{{ gluster_backup_dir }}"
      - "{{ check_dir }}"


- name: create gluster mount dir
  file:
    name: "{{ gluster_backup_dir }}"
    state: directory
  when: not check_dir.stat.exists


- name: mount gluster shared storage
  mount:
    name: "{{ gluster_backup_dir }}"
    src: "{{ keepalive_virtual_ipaddress }}:/{{ gluster_brick_name }}"
    fstype: glusterfs
    opts: "defaults,_netdev,backupvolfile-server={{ keepalive_virtual_ipaddress }}"
    state: mounted

- name: backup script
  template:
    src: backupscript.sh.j2
    dest: /opt/backupscript.sh
    mode: '0744'
    owner: root
    group: root

- name: config bacup script
  lineinfile:
    path: /etc/crontab
    line: "*/5 * * * * root   bash +x /opt/backupscript.sh"