---
# tasks file for provision/roles/nc-haproxy

- name: HAPROXY | install IUS repo
  yum:
    name: https://repo.ius.io/ius-release-el7.rpm
    state: present

- name: HAPROXY | install haproxy
  yum:
    name: haproxy20
    state: present

- name: HAPROXY | deploy haproxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    validate: /usr/sbin/haproxy -c -f %s
  notify: restart haproxy

- name: HAPROXY | Logging config step 1
  lineinfile:
      path: /etc/rsyslog.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
  with_items:
    - { regexp: '^#$ModLoad imudp' , line: '$ModLoad imudp'  }
    - { regexp: '^#$ModLoad imtcp' , line: '$ModLoad imtcp' }
    - { regexp: '^#$UDPServerRun 514' , line: '$UDPServerRun 514' }
    - { regexp: '^#$InputTCPServerRun 514' , line: '$InputTCPServerRun 514' }

- name: HAPROXY | Logging config step 2
  lineinfile:
      path: "{{ item.path }}"
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
  with_items:
    - { path: /etc/sysconfig/rsyslog , regexp: '^SYSLOGD_OPTIONS=' , line: 'SYSLOGD_OPTIONS="-c 2 -r"' }

- name: HAPROXY | Logging config step 3
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.d/haproxy.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart_rsyslog
