---
ntp_timezone: Europe/Moscow
domain: cloud16.home
#nfs_server_allow_host: 192.168.11.161



mntfolder: /nfs
nfsserver_host: 192.168.11.160
datafolder: /datadrive

ansible_user: vagrant
ansible_ssh_private_key_file: /vagrant/ansible.pem





...
