---
ntp_timezone: Europe/Moscow
domain: cloud16.home
#nfs_server_allow_host: 192.168.11.161



mntfolder: /nfs
nfsserver_host: 192.168.11.160
datafolder: /datadrive

logstash_bits_port: 5044
filebeat_logstash_server: "{{ groups.kibana[0] }}.{{ domain }}:{{ logstash_bits_port }}"
filebeat_version: 7.6.2
ansible_user: vagrant
ansible_ssh_private_key_file: /vagrant/ansible.pem



mongodb_user_backup: dbuser_backup
mongodb_user_backup_pass: dbuser_backup
mongodb_user_exporter: dbuser_exporter
mongodb_user_exporter_pass: dbuser_exporter
mongodb_user_cer: dbuser_cer
mongodb_user_cer_pass: dbuser_cer
mongodb_router:
  - "{{ groups.mongodb_router[0] }}"
  - "{{ groups.mongodb_router[1] }}"
  - "{{ groups.mongodb_router[2] }}"

gluster_backup_dir: /databackup
gluster_host: "{{ groups.gluster[0] }}"
gluster_brick_name: gv0
cer_db: cer
node_exporter_mongo_user: mongodb_exporter
node_exporter_mongo_group: mongodb_exporter
...
