---
# defaults file for provision/roles/nc-gluster-setup
gluster_brick_dir: /datadrive/gluster/brick
gluster_brick_vol: /datadrive/gluster/brick/gv0

gluster_mount_dir: /mnt/
gluster_cluster_hosts:
  - "{{ groups.gluster[0] }}"
  - "{{ groups.gluster[1] }}"

filebeat_index: filebeat-gluster
filebeat_path_log: "{{ mongodb_log }}"
filebeat_app_name: gluster

keepalive_virtual_ipaddress: 172.20.1.40