---
haproxy_port: '80'
haproxy_log_path: /var/log/haproxy.log
# haproxy_username: 'stat'
# haproxy_password: 'statpass'

keepalive_interface: eth1
#keepalive_virtual_router_id: 1
keepalive_virtual_ipaddress: 172.20.1.100



filebeat_path_log: "{{ haproxy_log_path }}"
filebeat_path_error:
filebeat_app_name: haproxy
filebeat_index: filebeat-haproxy