mongodb_router_port: "{{ 27017 | string }}"
mongodb_version: 4.0.18
mongodb_datadrive: /datadrive/mongodb
mongodb_user: mongod
mongodb_masters:
  - "{{ groups.mongodb_config[0] }}"
  - "{{ groups.mongodb_shard1[0] }}"
  - "{{ groups.mongodb_shard2[0] }}"

mongodb_log_path: /var/log/mongodb
mongodb_log: "{{ mongodb_log_path }}/mongod.log "
mongodb_conf_pidFile: /var/run/mongodb
mongodb_pid: "{{ mongodb_conf_pidFile }}/mongod.pid"
filebeat_path_log: "{{ mongodb_log }}"
filebeat_index: filebeat-mongodb
filebeat_app_name: mongodb
