---
# tasks file for grafana

- name: Add grafana repo
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  with_items:
    - { src: grafana.repo.j2 , dest: /etc/yum.repos.d/grafana.repo }

- name: Install Grafana
  yum:
    name: grafana
    state: present

- name: Tepmlate database
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
    owner: grafana
    group: grafana
  with_items:
    - { src: files/grafana.db , dest: /var/lib/grafana/grafana.db }


- name: Install/update Grafana panels\plugin
  command: grafana-cli plugins install "{{ item }}"
  with_items:
    - "{{ grafana_panels }}"
  notify: grafana_restart

- name: Allow port {{ mongodb_port }} in firewalld
  firewalld:
    port: "{{ grafana_port }}/tcp"
    permanent: yes
    state: enabled

- name: Check  Firewalld  is Enabled and started
  systemd:
    name: firewalld
    state: restarted
    enabled: true

- name: Enable grafana
  systemd:
    name: grafana-server
    state: started
    daemon_reload: yes
    enabled: true
