galaxy_info:
  author: Agafonov Andrey
  description: Deploy mongodb  init replica set
  company:  "cloud16.ru"
  min_ansible_version: 2.9
  galaxy_tags:
    - mongodb
    - mongodb_replica_set
dependencies:
  - prepare
  - mongodb-base

