---
# tasks file for mongodb-replicaset
- name: MONGODB-REPLICASET | Install python dependence
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - gcc
    - python-devel

- name: MONGODB-REPLICASET |crete SSL Key for replicaset
  copy:
    src: files/mongodb-ssl
      #{{ mongodb_replicaset_name }}
    dest: /etc/ssl/mongodb-keyfile
    owner: "{{ mongodb_user }}"
    group: "{{ mongodb_user }}"
    mode: '0400'

- name: MONGODB-REPLICASET | Install pip PyMongo
  command: pip install pymongo

- name: MONGODB-REPLICASET | Enable SSL Connection in config mongodb
  replace:
      path: /etc/mongod.conf
      regexp: "{{ item.regexp }}"
      replace: "{{ item.replace }}"
      owner: root
      group: root
      mode: '0644'
      backup: yes
  with_items:
    - { regexp: '^#security:', replace: 'security:' }
    - { regexp: '^#  keyFile: /etc/ssl/mongodb-keyfile', replace: '  keyFile: /etc/ssl/mongodb-keyfile' }
  # notify:
  #   - restart_mongodb

- name: MONGODB-REPLICASET | restart_mongodb
  systemd:
    name: mongod
    enabled: yes
    state: restarted

    #name: pymongo
    #state: present

- name: MONGODB-REPLICASET |Config Replica set {{ mongodb_replicaset_name }}
  template:
    src: "{{ hostvars[inventory_hostname].group_names[1] }}.js.j2"
    dest: /tmp/initrs.js
  when: (inventory_hostname in mongodb_masters)


- name: MONGODB-REPLICASET |Init Replica set {{ mongodb_replicaset_name }}
  shell: 'mongo --host localhost --port {{ mongodb_port }}  </tmp/initrs.js'
  when:  (inventory_hostname in mongodb_masters)

- name: MONGODB-REPLICASET | Pause reaplica set make voting
  pause:
    seconds: 30

- name: MONGODB-REPLICASET | Check ReplicaSet is master
  command: echo "rs.status().members[0].stateStr" | mongo  --port {{ mongodb_port }} --quiet
  retries: 60
  delay: 5
  register: result
  until: result.rc != "PRIMARY"
  when:  (inventory_hostname in mongodb_masters)


- name: MONGODB-REPLICASET | Create {{ mongodb_database_user }} user for ReplicaSet
  mongodb_user:
    database: admin
    name: "{{ mongodb_database_user }}"
    password: "{{ mongodb_database_password }}"
    login_port: "{{ mongodb_port }}"
    state: present
    roles: root
  when: (inventory_hostname in mongodb_masters)

