---
- name: install mongod
  hosts: mongodb
  become: true
  gather_facts: yes
  roles:
    - mongodb-sh

- name: Deploy GlusterFS nodes
  hosts: gluster
  become: yes
  roles:
    - gluster-setup
    - keepalived
#     ## - gluster-run


- name: Deploy HAProxy
  hosts: haproxy
  become: yes
  roles:
    - keepalived
    - haproxy

# - name: Deploy cer
#   hosts: cer
#   become: yes
#   roles:
#     - cer

- name: Deploy filebeat
  hosts:
    - mongodb
    - haproxy


  become: yes
  roles:
    - filebeat

- name: Deploy Kibana
  hosts: kibana
  become: yes
  roles:
    - kibana

- name: backup
  hosts: backup
  become: yes
  roles:
    - backup


  #   - name: setup backend1
  # hosts: backend1
  # become: yes
  # roles:
  #   - nc-gluster-client
  #   - nc-nginx
  #   #    - nc-netdata-slave
  #   - nc-backup-user
  #   - nc-restic
  #   - nc-redis
  #   - nc-php
  #   - nc-mysql