---
- name: Prepare machines
  hosts: all
  become: true
  become_method: sudo
  gather_facts: yes
  roles:
    - prepare

- name: Deploy shared MongoDB Cluster
  hosts: mongodb
  become: true
  become_method: sudo
  gather_facts: yes
  roles:
    - mongodb-sh

- name: Deploy GlusterFS nodes
  hosts: gluster
  become: yes
  roles:
    - keepalived
    - gluster-setup

- name: Deploy HAProxy
  hosts: haproxy
  become: yes
  roles:
    - keepalived
    - haproxy

- name: Deploy cer
  hosts: cer
  become: yes
  roles:
    - cer

- name: Deploy logging tools
  hosts:
    - mongodb
    - haproxy
    - gluster
    - cer
  become: yes
  roles:
    - filebeat

- name: Deploy Kibana
  hosts: kibana
  become: yes
  roles:
    - kibana

- name: backup
  hosts: backup
  become: yes
  roles:
    - backup


- name: install node-exporter
  hosts:
    - all
  become: true
  gather_facts: yes
  roles:
    - node-exporter

- name: install node-exporter for mongo specify metrics
  hosts: mongodb
  become: true
  gather_facts: yes
  roles:
    - node-exporter-mongodb


- name: install prometheus
  hosts: prometheus
  become: true
  gather_facts: yes
  roles:
    - prometheus
    - grafana



################################
# - name: restore
#   hosts: backup
#   become: yes
#   roles:
#     - restore