---
# handlers file for provision/roles/nc-haproxy

- name: restart haproxy
  service:
    name: haproxy
    state: restarted
    enabled: yes

- name: restart_rsyslog
  service:
    name: rsyslog
    state: restarted

